/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as AuthYoutubeCallbackRouteImport } from './routes/auth.youtube.callback'
import { Route as AuthInstagramCallbackRouteImport } from './routes/auth.instagram.callback'
import { Route as ApiCronProcessScheduledRouteImport } from './routes/api.cron.process-scheduled'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthYoutubeCallbackRoute = AuthYoutubeCallbackRouteImport.update({
  id: '/auth/youtube/callback',
  path: '/auth/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInstagramCallbackRoute = AuthInstagramCallbackRouteImport.update({
  id: '/auth/instagram/callback',
  path: '/auth/instagram/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProcessScheduledRoute = ApiCronProcessScheduledRouteImport.update({
  id: '/api/cron/process-scheduled',
  path: '/api/cron/process-scheduled',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/cron/process-scheduled': typeof ApiCronProcessScheduledRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/auth/youtube/callback': typeof AuthYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/cron/process-scheduled': typeof ApiCronProcessScheduledRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/auth/youtube/callback': typeof AuthYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/cron/process-scheduled': typeof ApiCronProcessScheduledRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/auth/youtube/callback': typeof AuthYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/upload'
    | '/api/cron/process-scheduled'
    | '/auth/instagram/callback'
    | '/auth/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/upload'
    | '/api/cron/process-scheduled'
    | '/auth/instagram/callback'
    | '/auth/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/upload'
    | '/api/cron/process-scheduled'
    | '/auth/instagram/callback'
    | '/auth/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiCronProcessScheduledRoute: typeof ApiCronProcessScheduledRoute
  AuthInstagramCallbackRoute: typeof AuthInstagramCallbackRoute
  AuthYoutubeCallbackRoute: typeof AuthYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/youtube/callback': {
      id: '/auth/youtube/callback'
      path: '/auth/youtube/callback'
      fullPath: '/auth/youtube/callback'
      preLoaderRoute: typeof AuthYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/instagram/callback': {
      id: '/auth/instagram/callback'
      path: '/auth/instagram/callback'
      fullPath: '/auth/instagram/callback'
      preLoaderRoute: typeof AuthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-scheduled': {
      id: '/api/cron/process-scheduled'
      path: '/api/cron/process-scheduled'
      fullPath: '/api/cron/process-scheduled'
      preLoaderRoute: typeof ApiCronProcessScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiCronProcessScheduledRoute: ApiCronProcessScheduledRoute,
  AuthInstagramCallbackRoute: AuthInstagramCallbackRoute,
  AuthYoutubeCallbackRoute: AuthYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
